### ISSUE TITLE
People who aren't cheaters

### ISSUE THREAD

**Issue by D3stroy3r108** [337557380/AceCombat7-cheaters#4]
I know some of the people you recently added. Ihr, Asetri 2 Pan, Wambo, and heinrich. I've played with all of them many times. None are cheaters. They are simply better players. Wambo is a relatively inexperienced player, just looking to get better. Ihr_ , Pan, and heinrich are just on a different level than most. If they're on here for that, then I should be too. My steam is the same as my profile here. Add me if you want, but the disrespect to fellow aces is appalling.

**Comment by ForeverAM** [comment]
I won't randomly add anyone to the list. Anyone on the list is confirmed, and I even wrote a Very Bad Note to lhr. Guess why.
Not just me, but many people have seen them cheating. My standards for identifying cheaters are very lenient, as long as you are not attacking casual players or possibly due to forgetting to uninstall something, only occasionally, and immediately exit the game after discovering the problem, I will not consider it malicious cheating. The people who can be added to the list are all very frequent and definitely intentionally cheating.
You are able to know so many cheaters at the same time and claim that they did not cheat. It may be because you have played less games and lack judgment, not noticing any abnormalities when encountering cheaters. It may also be because they are your friends and did not attack you or cheat in front of you. Alternatively, they may have installed certain mods themselves without realizing that they are cheating.
If you know them and they really didn't intend to cheat, please convey some message on my behalf, check if the mods you installed will take effect in MP, and uninstall these mods when playing MP. The names already on the list do not mean they will not be erased. After discovering that they have played the game normally enough times, I will erase their names. Of course, these words are not meant for lhr. lhr has already carried out massacres in various rooms and used cheating programs to lock in health points. He is an absolute cheater.
Try to play and communicate with cheaters as little as possible, Wishing bro  a have fun!

**Comment by D3stroy3r108** [comment]
Ihr is not my friend. He is a lobby crusher though. It may be that he cheats, or simply that he is THAT good. Idk, the profile is private, and he's made no attempt at responding to me. I can say that I've never seen him "lock his hp". I worked my ass off to get even one hit per match. And when I did, it always registered. His plane is also statistically better than what I use. Couple that with good game sense, and that's a real good ace.
Same for heinrich, but I can beat heinrich, so... ? 
Pan I've known for a while. One of the people who helped me get where I am. No way, no matter what you say, will I believe they cheat. IEWS is not cheating. I've interacted with Pan directly for over a year now, having only gotten my ass beat in his lobbies prior. Chill to talk to, as well.
Wambo is someone I randomly met recently and had a great 1v1. I won, but that's mostly due to experience. Seems like a nice person, but, you're right, my experience with them is limited. They are quite pleasant to talk to though, so if you try and talk to them, you might get a favorable outcome.
Some of them may use mods. I use mods and just never turn them off, since there's no real need to. None of them affect multiplayer, as they are either skin mods or ai enhancements. Occasionally, it will look like my msl explodes on a target, or one of theirs hits me, but it just doesnt register. Never thought they were cheating, simply that the msl ran out before hitting, but still played the explosion effect. This has been happening for a couple years now, and not one of my friends has brought it to my attention.
I have played this game for 4 years. My judgement, especially of character, is sound. Maybe try talking to these folks, at least Pan and Wambo, and maybe, just maybe, you guys can resolve this. Besmirching their names without given the chance to prove themselves innocent is, well, stupid. 
I will communicate with whoever I wish. I believe they are innocent, so I shall treat them as such. You're welcome to fly with us though, and see for yourself.

**Comment by ForeverAM** [comment]
Ihr_Schatten_1018 uses a modified weapon that can instantly kill anyone on the field, often achieving victory within seconds of entering certain rooms. If you also use a cheat weapon to deal with him, he will lock in health points

https://github.com/user-attachments/assets/d6814c4e-07e4-401a-b656-cc6ee8350d56

https://github.com/user-attachments/assets/4e08f3ce-c8a1-4a53-b40a-ab7cb8ef07a3

ASETRI 2 PAN modified maneuverability and missile performance, and locked in health points. This is a partial video
This blogger wants to report ASETRI 2 PAN's friend Archer 1 Burns together, but I haven't received conclusive evidence, so I didn't include Burns on the list

https://github.com/user-attachments/assets/89b81788-21ca-486c-8fa7-1cd716f17dcb


https://www.bilibili.com/video/BV13xSqYsERa/


I didn't save heinrich's video, his weapon has no cooldown time


♥Oriana ♥ Using Unrestricted PSM, someone posted his video on the community, but the video has expired
![wb2](https://github.com/user-attachments/assets/7a9aea08-66bd-48c8-86e2-c9534d5a38e0)
![wb1](https://github.com/user-attachments/assets/39be39b1-3e9d-4fea-a994-7edab2f8ce18)

It's difficult for me to save everyone's videos, Because the number of cheaters is endless, my ways of obtaining information are also varied. The name of the cheater will also change frequently, which will make it different from the cheater's name in the video. If I want to accurately record every cheater in the video, it will cost me a huge amount of cost
So after confirmation, usually I only write them on the list and don't save the video

**Comment by D3stroy3r108** [comment]
I see. I have nothing to add beyond this from Asetri 2 Pan:

"Ok after watching that video myself i can conclude i was cheating. It was unintentionally though and I would like to apologize to the reporter, the cheaterlist owner and the AC community as a whole. I had the Skies Rebalanced v1.2E mod installed for the increased the difficulty of single player and its just one of those days i was a complete dumb dumbhead. I didnt check my files and uninstall them before playing MP. I believe the files i had on was the:

- SKIES_REBALANCED 1.2E (NON-DRIFT EDITION)\planestatschange\skiesrebalanced_planestatschange_Typhoon_WITHOUT DRIFT_P.pak

According to the mod this gave the Typhoon "slightly worse mobility than Mirage 2000-5, better engine performance than Rafale M"

I test flew the Typhoon and i havent even notice a not even a slight increase in performance from the mod for the Typhoon. It could be me but you can try the mod for yourself and see what i mean. I also live on a military base (FT SILL) and our internet is pretty bad here, sometimes i experience lag surges where i see everyone is skipping across my screen everywhere and i assume its happening on there end where they see me skipping.

Lastly I had the Stonehenge map swap mod enabled which switches Roca Roja MP with Stonehenge.

At the time before the date of the video i didnt think a map swap effected mp much but my friends and I think what happened is stonehenge is a bigger map than Roja and what it appears on other ppl's screen is im flying out of bounce. At least thats what i think is happening i dont know much abt modding to know what is actually going on behind the scene."

**Comment by ForeverAM** [comment]
If it's not intentional, i can remove him from the list, just don't do it again in the future

**Comment by ForeverAM** [comment]
Asetri 2 Pan continued to use the modified map even after realizing that it was a wrong behavior. The result of changing the map is that it can ignore the terrain of the original map, which is considered cheating in some cases. Could you please help me convey this message to him

https://files.catbox.moe/5jqycb.mp4
![微信图片_20241123114255](https://github.com/user-attachments/assets/e4df71e0-f976-4ebb-a8e5-d4572922ac14)

**Comment by D3stroy3r108** [comment]
Done
